### ISSUE TITLE
Phase out no-BODY POST in net/api.

### ISSUE THREAD

**Issue by dkorolev** [KnowSheet/Bricks#105]
Pending @deathbaba @sompylasar @mzhurovich approval, implicit in 24 hours.

Thanks,
Dima

**Comment by sompylasar** [comment]
@dkorolev I approve.

**Comment by deathbaba** [comment]
Hey, my platform http wrapper already has something like
```
  if (body data in params) POST(); else GET();
```
POST with no body doesn't make any sense.

**Comment by sompylasar** [comment]
> Hey, my platform http wrapper already has something like
>
>    if (body data in params) POST(); else GET();
> 
> POST with no body doesn't make any sense.

Well, HTTP verb should not depend on having or not having a body, it is a separate parameter of the request. There is, e.g. a HEAD or an OPTIONS request — they have no body, too.

**Comment by dkorolev** [comment]
+1 on HTTP verb not depending on the body (FTR, @mzhurovich already made the change).

I do, however, agree that the logic Alex used has indeed proved unambiguous: We don't allow BODY for GET-s and require BODY for POST-s.

**Comment by dkorolev** [comment]
Will remove it. On my plate. Closing the issue now.
