### ISSUE TITLE
Default error responses are sent as "text/plain" but the content is HTML

### ISSUE THREAD

**Issue by sompylasar** [KnowSheet/Bricks#124]
Default error responses are sent as "text/plain":
https://github.com/KnowSheet/Bricks/blob/master/net/api/impl/posix_server.h#L209
```
        r.connection.SendHTTPResponse(
            DefaultMethodNotAllowedMessage(), HTTPResponseCode.MethodNotAllowed, "text/plain");
```
...or without a content-type which defaults to "text/plain":
https://github.com/KnowSheet/Bricks/blob/master/net/api/impl/posix_server.h#L293
```
          connection->SendHTTPResponse(DefaultFourOhFourMessage(), HTTPResponseCode.NotFound);
```

Here are the HTML messages:
https://github.com/KnowSheet/Bricks/blob/master/net/http/default_messages.h#L39
```
inline std::string DefaultFourOhFourMessage() { return "<h1>NOT FOUND</h1>\n"; }
inline std::string DefaultInternalServerErrorMessage() { return "<h1>INTERNAL SERVER ERROR</h1>\n"; }
inline std::string DefaultMethodNotAllowedMessage() { return "<h1>METHOD NOT ALLOWED</h1>\n"; }
```

The only message that is sent correctly (with "text/html") is the `DefaultInternalServerErrorMessage`:
https://github.com/KnowSheet/Bricks/blob/master/net/http/impl/server.h#L354
```
        SendHTTPResponse(
            DefaultInternalServerErrorMessage(), HTTPResponseCode.InternalServerError, "text/html");
```

**Comment by dkorolev** [comment]
Already fixed in development, pull request to follow within ~14 hours.

Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by sompylasar** [comment]
@dkorolev Thanks, then I'll fix it in my JS rewrite, too.

**Comment by sompylasar** [comment]
Was fixed via https://github.com/KnowSheet/Bricks/commit/4b87a9a1aacba6d8c178c44a3777cfa2a0ce07a2

**Comment by dkorolev** [comment]
:+1:
