### ISSUE TITLE
net/http: No test coverage for extra_headers in the module's own tests

### ISSUE THREAD

**Issue by sompylasar** [KnowSheet/Bricks#57]
In the tests located under `net/http` module.
The `extra_headers` are only used in some tests that are run from the root directory.

**Comment by dkorolev** [comment]
Roger that, thank you.

**Comment by dkorolev** [comment]
Ref. https://github.com/KnowSheet/Bricks/pull/58

Strictly speaking, a) this is unnecessary (coverage report is not designed to only make sense project-wide), and b) if this has to be fixed, a few exception throws should also be tested as well.

Regardless, here's the fix :-)

Thanks,
Dima

**Comment by sompylasar** [comment]
a) my observations aren't based on a coverage report, I just wanted to copy
the API usage pattern to my code (the tests are some sort of docs);
b) sure, would be nice, too.

**Comment by dkorolev** [comment]
I too like the tests serve as the documentation. See an updated pull request; no exceptions tested though.

**Comment by dkorolev** [comment]
Just looked through the code and I believe this one is taken care of in the `SmokeWithHeaders` test in `net/http/test.cc`.
